# Generated by Django 5.1.4 on 2026-02-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_age_user_id_alter_hobbies_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregister',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
