# Generated by Django 5.1.4 on 2026-02-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customerregister_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='age', to='main.customerregister'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobby', to='main.customerregister'),
        ),
    ]
