# Generated by Django 5.1.4 on 2026-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_age_user_id_alter_hobbies_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregister',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
