# Generated by Django 5.1.4 on 2026-02-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customerregister_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregister',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
