# Generated by Django 5.1.4 on 2026-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customerregister_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregister',
            name='password',
            field=models.TextField(),
        ),
    ]
